Allow configuring BentoML via CLI (#220)
* print error instead of raising exception

* restructure deployment related CLI code

* formatting

* nit

* rename

* update log module for setting bentoml library log level

* add --quiet and --debug options for bentoml CLI

* update _echo util method

* formatting / renaming

* config related commands

* add notes on local development

* help info update

* lint & formatting changes

* nits

* fix cli error: bentoml_cli() missing 1 required positional argument